import { Component } from '@angular/core';
import {
  APPENDIX_BLOB,
  BORKED_ELIXR_MTM_DTM_SURVEY,
  FAKE_ENG_WITH_CAREPLUS_APPENDIX,
  HELLO_WORLD_BLOB,
  FULL_CMR_BLOB,
} from './constants';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'my-app';

  /*
    Local PDF Paths
    (uncomment whichever you'd like to be used as src)
  */

  // PDF of powerpoint containing images, tables, etc
  // mySrc = 'assets/pdfs/Bootstrap-vs-Material-Design-vs-Prime-vs-Tailwind.pdf';

  // PDF having errors (renders fine locally but not when given as base64 string)
  // mySrc = 'assets/pdfs/Elixir MTM-DTM Survey_08.12.2022.pdf';

  // Appendix from cmr containing many language chars
  // mySrc = 'assets/pdfs/CarePlus 2021 ENSP Disclaimer.pdf';

  // Generated english PDF from workflow-pdf-service
  // mySrc = 'assets/pdfs/fakeEnglishData.pdf';

  // Generated PDF from workflow-pdf-service but appendix replaced with Careplus appendix before generated
  // mySrc = 'assets/pdfs/fakeEnglishDataWithCareplusAppendix.pdf';

  // Generated english PDF from workflow-pdf-service
  // mySrc = 'assets/pdfs/fakeSpanishData.pdf';

  //
  //
  //

  /*
    BASE64 ENCODED STRINGS 
    (uncomment whichever you'd like to be used as base64Src)
  */

  // Simple document displaying hello world for test
  // myBase64Src = HELLO_WORLD_BLOB;

  // Careplus appendix (many language chars, accents, etc)
  // myBase64Src = APPENDIX_BLOB;

  // Encoded Elixir MTM-DTM Survey 8/12/22 pdf (still doesn't render correctly)
  // myBase64Src = BORKED_ELIXR_MTM_DTM_SURVEY;

  // Encoded payload for full CMR
  // myBase64Src = FULL_CMR_BLOB;

  /* 
  Fake English Data With Careplus Appendix
      Generated by replacing the base64 encoded string within fakeEnglishData 
      from workflow-pdf-service with APPENDIX_BLOB. 
      No issues generating or rendering the file.
  */
  myBase64Src = FAKE_ENG_WITH_CAREPLUS_APPENDIX;
}
